name: flutter_cinemapedia
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.6.2
  intl: ^0.20.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1


flutter:
  uses-material-design: true

  assets:
    - .env
